name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies (including dev)
        run: poetry install --with dev
      - name: Lint
        run: poetry run flake8 src
      - name: Run tests with coverage
        run: poetry run pytest --cov=papercruncher