name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - run: pip install poetry
      - run: poetry install --with dev
      - name: Lint
        run: poetry run flake8 src
      - name: Add src to PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}/src" >> $GITHUB_ENV
      - name: Run tests with coverage
        run: poetry run pytest --disable-warnings --maxfail=1 --cov=papercruncher